// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynmcpoauuvigqonbwgoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlubWNwb2F1dXZpZ3FvbmJ3Z29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MDQ4ODYsImV4cCI6MjA4OTA4MDg4Nn0.lqN2h75fUk9UVaD6Cflr5ZLKwUi6jYdFAFY_-Xio1nA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});